### ISSUE TITLE
Use proper error reporting

### ISSUE THREAD

**Issue by Munsio** [karriereat/plantuml-static#8]
Instead of `panic()` we should return proper errors and handle them correctly.

**Comment by Slemgrim** [comment]
We differ between runtime errors and startup errors

Almost everything that happens during the http requests should be recoverable and therefore return proper errors. We can handle them and keep the service alive by returning proper http status codes. 

We also have errors that won't allow the application to run in a valid state or are simple not recoverable. E.g. missing config, invalid repository, no PlantUML server. Those errors SHOULD always stop the application. But you're right, a `log.Fatal()` would be better than `panic()` all the time
